application: thrudlookinglass
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- remote_api: on
- appstats: on

includes:
- mapreduce/include.yaml

handlers:
- url: /pull_facebook_data
  script: user_data.pull_data.app

- url: /authenticate/.*
  script: handlers.web.authentication.app

- url: /
  script: handlers.web.index.app

- url: /visualise
  script: handlers.web.index.app

- url: /visualisation_data
  script: handlers.rest.visualise.app

- url: /assets/js
  static_dir: assets/js

- url: /assets/css
  static_dir: assets/css

libraries:
- name: django
  version: "1.4"
- name: numpy
  version: "latest"
- name: matplotlib
  version: "1.2.0"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
