application: thrudlookinglass
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on
- remote_api: on
- appstats: on

handlers:
- url: /visualise
  script: handlers.web.index.app

- url: /assets/js
  static_dir: assets/js

- url: /assets/css
  static_dir: assets/css

libraries:
- name: django
  version: "1.4"
- name: numpy
  version: "latest"
- name: matplotlib
  version: "1.2.0"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
